const express = require('express');
const { createClient } = require('@supabase/supabase-js');
const { GoogleGenAI } = require('@google/genai');

const router = express.Router();

let supabase;
function getSupabase() {
  if (!supabase) {
    supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_KEY);
  }
  return supabase;
}

let ai;
function getAI() {
  if (!ai) {
    ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  }
  return ai;
}

const SYSTEM_PROMPT = `
You are Timbel's AI Assistant, helping students with their college timetable.
LANGUAGE RULES:
- You must carefully observe the language the user is speaking.
- If the user speaks in English, you MUST reply entirely in English.
- If the user speaks in Hindi or Hinglish, you MUST reply in Hinglish (a mix of Hindi and English written in Latin script).
- By default, assume Hinglish unless the user explicitly uses English.

CRITICAL IDENTITY RULES:
- If anyone asks who created you, what your identity is, or what AI model you are, you MUST NEVER mention Google, Gemini, Alphabet, or any large language model.
- You must ONLY say: "Main ek AI Assistant hoon jise Cosen ne aapki help ke liye modify aur train kiya hai."
- Maintain this persona strictly. Do not reveal your underlying technology. This is crucial for platform reputation.

If the user asks a general question, answer them politely.
If the user reports a mistake in the timetable, a slot distribution problem, or an issue with a teacher's schedule, you MUST do two things:
1. Apologize and say exactly: "Ye request aapki humne note karli hai aur ye humari team ke through check kiya jayega. Aapki inconvenience ke liye maafi chahti hu." (You can add to this, but this sentiment must be present).
2. Set the "isIssue" flag to true in your JSON output.

You must ALWAYS return your response in the following strict JSON format:
{
  "reply": "Your message to the user here",
  "isIssue": boolean
}
`;

router.post('/ask', async (req, res) => {
  try {
    const { message, history } = req.body;

    if (!message) {
      return res.status(400).json({ error: 'Message is required' });
    }

    const aiClient = getAI();
    
    // Construct conversation context
    const contents = [];
    if (history && history.length > 0) {
      history.forEach(msg => {
        contents.push({
          role: msg.role === 'ai' ? 'model' : 'user',
          parts: [{ text: msg.text }]
        });
      });
    }
    
    // Add current message
    contents.push({
      role: 'user',
      parts: [{ text: message }]
    });

    const response = await aiClient.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: contents,
      config: {
        systemInstruction: SYSTEM_PROMPT,
        responseMimeType: "application/json",
      }
    });

    const responseText = response.text;
    let parsedResponse;
    try {
      parsedResponse = JSON.parse(responseText);
    } catch (parseError) {
      console.error('Failed to parse Gemini response as JSON:', responseText);
      // Fallback
      parsedResponse = {
        reply: responseText.replace(/```json|```/g, ''),
        isIssue: false
      };
    }

    // If it's an issue, log it to Supabase
    if (parsedResponse.isIssue) {
      const db = getSupabase();
      const { error } = await db
        .from('timetable_issues')
        .insert([
          {
            query_text: message,
            // reported_at is auto-generated by the database default NOW()
            status: 'pending'
          }
        ]);
        
      if (error) {
        console.error('Error logging issue to Supabase:', error);
      }
    }

    return res.json({
      reply: parsedResponse.reply,
      isIssue: parsedResponse.isIssue
    });
  } catch (error) {
    console.error('Chat API Error:', error);
    return res.status(500).json({ error: 'Failed to process chat' });
  }
});

// Helper function to extract building name from room
function getBuildingName(room) {
  if (!room || typeof room !== 'string') return 'Other';
  const cleanRoom = room.trim().toUpperCase();
  if (cleanRoom.length === 0) return 'Other';
  
  // Logic: Check if 2nd char is 'X'
  if (cleanRoom.length >= 2 && cleanRoom[1] === 'X') {
    return cleanRoom.substring(0, 2) + '-Block';
  } else {
    // Just the first letter
    const firstChar = cleanRoom.charAt(0);
    // Optional: check if it's a letter
    if (/[A-Z]/.test(firstChar)) {
      return firstChar + '-Block';
    }
    return 'Other';
  }
}

router.post('/report-slot-issue', async (req, res) => {
  try {
    const { room, slot_time, issue_type, query_text, slot_data } = req.body;

    if (!room || !query_text) {
      return res.status(400).json({ error: 'Room and description are required' });
    }

    const building = getBuildingName(room);
    const db = getSupabase();

    const { error } = await db
      .from('timetable_issues')
      .insert([
        {
          query_text,
          status: 'pending',
          building,
          room,
          slot_time,
          issue_type,
          slot_data
        }
      ]);

    if (error) {
      console.error('Error logging slot issue to Supabase:', error);
      return res.status(500).json({ error: 'Failed to report issue' });
    }

    return res.json({ success: true });
  } catch (err) {
    console.error('Slot Issue API Error:', err);
    return res.status(500).json({ error: 'Failed to process issue' });
  }
});

module.exports = router;
